name: Run All Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright
        run: yarn playwright add --with-deps
      - name: Run Jest
        run: yarn run test
      - name: Run Playwright tests
        run: yarn run test:e2e
